[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, colorize

; Jika partisi dirasa tidak cukup (karena LVGL besar),
; disarankan menggunakan default_8MB.csv atau custom
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.partitions = default_8MB.csv

build_flags =
  -std=gnu++17
  -D ARDUINOJSON_ENABLE_ARDUINO_STRING=1
  -D CONFIG_ARDUHAL_LOG_COLORS=1
  -D CORE_DEBUG_LEVEL=3

  ; Native USB untuk CDC dan Sleep Detection PC
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

  ; --- Konfigurasi TFT_eSPI (Menghindari User_Setup.h) ---
  -D USER_SETUP_LOADED=1
  -D ILI9341_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=320

  ; Pin SPI untuk LCD TFT (FSPI / SPI2)
  -D TFT_MOSI=11
  -D TFT_SCLK=12
  -D TFT_CS=10
  -D TFT_DC=9
  -D TFT_RST=14
  -D TFT_BL=21

  ; Pengaturan SPI Font
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1
  -D SPI_FREQUENCY=40000000

  ; LVGL Configuration
  -D LV_CONF_SKIP=1
  -D LV_COLOR_DEPTH=16
  -D LV_USE_TFT_ESPI=1
  -D LV_FONT_MONTSERRAT_14=1

lib_ldf_mode = chain+
lib_compat_mode = strict

lib_deps =
  bblanchon/ArduinoJson @ ^7.4.2
  bodmer/TFT_eSPI @ ^2.5.43
  lvgl/lvgl @ ^9.2.0
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#master
